import DashboardLayout from '../../layouts/DashboardLayout.jsx';
import Icon from '../../components/Icon.jsx';
import Badge from '../../components/Badge.jsx';
import { ArrowLeft, Printer, TrendingUp, TrendingDown, DollarSign } from 'lucide';

export default function CashFlowReport({ transactions, stats, categories }) {
  return (
    <DashboardLayout title="Cash Flow Statement">
      <div class="flex flex-col gap-8">
        
        {/* Header */}
        <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 no-print">
          <div class="flex items-center gap-4">
            <a href="/dashboard/reports" class="btn btn-ghost btn-circle"><Icon icon={ArrowLeft} size={24} /></a>
            <div>
              <h1 class="text-3xl font-bold tracking-tight">Cash Flow Statement</h1>
              <p class="text-slate-500">Summary of all inflows and outflows.</p>
            </div>
          </div>
          <button class="btn btn-outline btn-sm gap-2" onClick="window.print()">
            <Icon icon={Printer} size={16} /> Print
          </button>
        </div>

        {/* Print Header */}
        <div class="hidden print:block text-center mb-8">
           <h1 class="text-2xl font-bold uppercase">Statement of Cash Flows</h1>
           <p class="text-sm">Period Ending: {new Date().toLocaleDateString()}</p>
           <div class="divider"></div>
        </div>

        {/* Big Stats */}
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
           <div class="stats shadow border border-base-200 bg-base-100">
              <div class="stat">
                <div class="stat-figure text-success"><Icon icon={TrendingUp} size={32} /></div>
                <div class="stat-title">Total Income</div>
                <div class="stat-value text-success text-2xl">{(stats.totalIncome || 0).toLocaleString()}</div>
                <div class="stat-desc">Deposits, Repayments, Shares</div>
              </div>
           </div>
           <div class="stats shadow border border-base-200 bg-base-100">
              <div class="stat">
                <div class="stat-figure text-error"><Icon icon={TrendingDown} size={32} /></div>
                <div class="stat-title">Total Expenses</div>
                <div class="stat-value text-error text-2xl">{(stats.totalExpense || 0).toLocaleString()}</div>
                <div class="stat-desc">Withdrawals, Disbursements</div>
              </div>
           </div>
           <div class="stats shadow border border-base-200 bg-base-100">
              <div class="stat">
                <div class="stat-figure text-primary"><Icon icon={DollarSign} size={32} /></div>
                <div class="stat-title">Net Cash Flow</div>
                <div class={`stat-value text-2xl ${stats.netCashFlow >= 0 ? 'text-primary' : 'text-warning'}`}>
                  {(stats.netCashFlow || 0).toLocaleString()}
                </div>
                <div class="stat-desc">Net Change in Cash</div>
              </div>
           </div>
        </div>

        {/* Breakdown Table */}
        <div class="card bg-base-100 border border-base-200 shadow-sm">
          <div class="card-body p-0">
            <div class="p-4 border-b border-base-200 bg-base-200/50 font-bold uppercase text-xs tracking-wider">Category Breakdown</div>
            <table class="table w-full">
              <tbody>
                {categories.map((cat, idx) => (
                  <tr key={idx} class="hover">
                    <td>
                      <div class="font-bold">{cat.name}</div>
                      <div class="text-xs opacity-50">{cat.count} transactions</div>
                    </td>
                    <td class="text-right">
                      <Badge type={cat.type === 'income' ? 'success' : 'error'}>
                        {cat.type}
                      </Badge>
                    </td>
                    <td class={`text-right font-mono font-bold ${cat.type === 'income' ? 'text-success' : 'text-error'}`}>
                      {cat.type === 'expense' ? '-' : '+'}{cat.amount.toLocaleString()} UGX
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer */}
        <div class="hidden print:block mt-20 text-center border-t pt-4 text-xs opacity-50">
           Generated by SACCO Management System
        </div>

      </div>
    </DashboardLayout>
  );
}
